=== FabioSenra/DWeb2019/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PR (header,grupo,resumo,deliverables,data) >
<!ELEMENT header (keyname,supervisor,titulo,subtitulo?,datai,dataf)>
<!ELEMENT supervisor (nome,homepage)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT homepage (#PCDATA) >
<!ELEMENT datai (#PCDATA) >
<!ELEMENT dataf (#PCDATA) >
<!ELEMENT grupo (elemento+) >
<!ELEMENT elemento (nome,numero,email?,git)>
<!ELEMENT resumo (#PCDATA | bold | italico | link)*>
<!ELEMENT bold (#PCDATA) >
<!ELEMENT link (#PCDATA) >
<!ELEMENT italico (#PCDATA) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT git (#PCDATA) >
<!ELEMENT deliverables (#PCDATA | link)* >
<!ELEMENT data (#PCDATA) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT subtitulo (#PCDATA) >
<!ELEMENT keyname (#PCDATA) >

=== FabioSenra/DWeb2019/TP2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "file:/Users/fabiosenra/Documents/MIEI-UM/DAW/DWeb2019/TP2/PR.dtd">
<PR>
    <header>
        <keyname>TP2-DAW</keyname>
        <supervisor>
            <nome>José Carlos Ramalho</nome>
            <homepage>http://www4.di.uminho.pt/~jcr/</homepage>
        </supervisor>
        <titulo>Trabalho prático 2ª semana</titulo>
        <datai>Setembro 2019</datai>
        <dataf>Outubro 2019</dataf>
    </header>
    <grupo>
        <elemento>
            <nome>Fábio Carvalho Senra</nome>
            <numero>A82108</numero>
            <git>https://github.com/FabioSenra</git>
        </elemento>
    </grupo>
    <resumo>
        O trabalho prático consistia na realização de dois DTD's e de um pequeno exercício sobre XPath.
        O primeiro DTD a realizar era sobre um Project Record exibido na aula. Depois de uma análise à estrutura dessa página foi considerado que esse se dividia em 5 partes essenciais um cabeçalho, autores, resumo, links dos ficheiros a serem entregues e por fim a data.
        Depois de analisar o arquivo XML dos arqueossitios foi concluído que o DTD seria bastante extenso e por essa razão realizou-se uma análise à ferramenta (Oxygen XML Editor), foi encontrado uma opção que permite a obtenção do DTD a partir do XML.
        Por fim, foi pedida também a realização de um exercício de consolidação sobre XPath sobre os arqueossitios.
    </resumo>
    <deliverables>
        <link>https://github.com/FabioSenra/DWeb2019/blob/master/TP2/PR.xml - Ficheiro XML de acordo com o DTD do PR realizado</link>
        <link>https://github.com/FabioSenra/DWeb2019/blob/master/TP2/PR.dtd - DTD do PR</link>
        <link>https://github.com/FabioSenra/DWeb2019/blob/master/TP2/arq.dtd - DTD dos arqueossitios</link>
        <link>https://github.com/FabioSenra/DWeb2019/blob/master/TP2/ex6 - Exercicio 6 da Ficha 3 sobre XPath</link>
    </deliverables>
    <data>26-09-2019</data>
</PR>
